from manim import *
import json
import math
from pathlib import Path

# ---------------------------------------------------------------------------
# Load timing/config generated by build.py
# ---------------------------------------------------------------------------
CONFIG_PATH = Path(__file__).with_name("config.json")
if CONFIG_PATH.exists():
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        CONFIG = json.load(f)
else:
    CONFIG = {"segments": []}

# ---------------------------------------------------------------------------
# Vertical 1080x1920 (Shorts format)
# ---------------------------------------------------------------------------
config.pixel_width = 1080
config.pixel_height = 1920
config.frame_width = 9
config.frame_height = 16
config.background_color = CONFIG.get("background_color", "#111111")

CIRCLE_RADIUS = CONFIG.get("circle_radius", 3.2)
R = CIRCLE_RADIUS
POINT_COLOR = CONFIG.get("point_color", "#FF5252")
LINE_COLOR = CONFIG.get("line_color", "#4FC3F7")
TEXT_COLOR = CONFIG.get("text_color", "#FFFFFF")
ACCENT = CONFIG.get("accent_color", "#FFD600")


def make_points(n: int) -> list[np.ndarray]:
    """Return n points on the circle in general position (no three chords concurrent)."""
    points = []
    for i in range(n):
        base = i * TAU / 6  # distribute 6 slots around the circle
        offset = 0.08 * math.sin(i * 2.1)
        angle = base + offset
        points.append(R * np.array([math.cos(angle), math.sin(angle), 0]))
    return points


class CircleDivision(Scene):
    def setup(self):
        self.circle = Circle(radius=R, color=LINE_COLOR, stroke_width=2.5)
        self.add(self.circle)
        self.points: list[Dot] = []
        self.lines: list[Line] = []
        self.count_label: Text | None = None
        self.caption: Text | None = None

    def construct(self):
        for seg in CONFIG.get("segments", []):
            stype = seg["type"]
            dur = float(seg.get("duration", 3.0))
            getattr(self, f"_seg_{stype}")(seg, dur)

    def _clear_caption(self):
        if self.caption is not None:
            self.play(FadeOut(self.caption), run_time=0.2)
            self.caption = None

    def _show_caption(self, text: str, dur: float, bottom: bool = True):
        self._clear_caption()
        self.caption = Text(text, font_size=38, color=TEXT_COLOR)
        if bottom:
            self.caption.to_edge(DOWN, buff=0.7)
        else:
            self.caption.to_edge(UP, buff=0.7)
        rt = min(0.5, dur * 0.25)
        self.play(FadeIn(self.caption, shift=UP * 0.15), run_time=rt)
        return rt

    def _seg_title(self, seg, dur):
        title = Text("Don't let it fool you!", font_size=70, color=ACCENT, weight=BOLD)
        subtitle = Text("Moser's circle problem", font_size=34, color=GRAY)
        subtitle.next_to(title, DOWN, buff=0.35)
        group = VGroup(title, subtitle)
        group.move_to(ORIGIN)

        ring = Circle(radius=R, color=LINE_COLOR, stroke_opacity=0.15)
        self.play(FadeIn(ring), Write(title), FadeIn(subtitle), run_time=1.0)
        self.wait(max(0.3, dur - 1.0))
        self.play(FadeOut(group), FadeOut(ring), run_time=0.4)

    def _seg_intro(self, seg, dur):
        rt = self._show_caption("A famous cautionary tale in math", dur)
        self.wait(max(0.3, dur - rt - 0.4))

    def _update_count(self, count: int, total_dur: float, after_rt: float):
        region_word = "region" if count == 1 else "regions"
        new_label = Text(f"{count} {region_word}", font_size=48, color=ACCENT, weight=BOLD)
        new_label.to_edge(DOWN, buff=1.6)

        used = 0
        if self.count_label is not None:
            self.play(Transform(self.count_label, new_label), run_time=0.5)
            used += 0.5
        else:
            self.play(FadeIn(new_label, shift=UP * 0.1), run_time=0.5)
            self.count_label = new_label
            used += 0.5

        wait = total_dur - after_rt - used - 0.2
        if wait > 0:
            self.wait(wait)

    def _seg_step(self, seg, dur):
        n = seg["n"]
        count = seg["count"]
        all_points = make_points(max(n, 6))
        target = all_points[n - 1]

        dot = Dot(target, color=POINT_COLOR, radius=0.09)
        self.points.append(dot)

        new_lines = []
        for prev_dot in self.points[:-1]:
            line = Line(prev_dot.get_center(), target, color=LINE_COLOR, stroke_width=2.2)
            self.lines.append(line)
            new_lines.append(line)

        # Fade out any lingering caption so the count label is clean
        self._clear_caption()

        # Animate the new point
        dot_rt = 0.25
        self.play(FadeIn(dot, scale=1.6), run_time=dot_rt)

        # Animate new chords sequentially
        if new_lines:
            per_line = max(0.12, min(0.25, (dur * 0.45 - dot_rt) / len(new_lines)))
            chord_rt = len(new_lines) * per_line
            self.play(LaggedStart(*[Create(l) for l in new_lines], lag_ratio=0.7, run_time=chord_rt))
        else:
            chord_rt = 0

        self._update_count(count, dur, dot_rt + chord_rt)

    def _seg_pattern(self, seg, dur):
        seq = seg.get("sequence", [1, 2, 4, 8, 16])
        items = []
        for i, val in enumerate(seq):
            t = Text(str(val), font_size=56, color=TEXT_COLOR)
            items.append(t)
            if i < len(seq) - 1:
                arrow = Text("×2", font_size=32, color=GRAY)
                items.append(arrow)

        group = VGroup(*items)
        group.arrange(RIGHT, buff=0.35)
        group.move_to(ORIGIN + UP * 1.2)

        self.play(LaggedStart(*[FadeIn(m, shift=UP * 0.15) for m in items], lag_ratio=0.3, run_time=1.5))

        caption_rt = self._show_caption("Each count is a power of two", dur, bottom=True)
        self.wait(max(0.3, dur - 1.5 - caption_rt - 0.4))
        self.play(FadeOut(group), run_time=0.3)

    def _seg_expect(self, seg, dur):
        n = seg["n"]
        wrong = seg.get("wrong_count", 32)
        all_points = make_points(max(n, 6))
        target = all_points[n - 1]

        self._clear_caption()

        dot = Dot(target, color=POINT_COLOR, radius=0.09)
        self.points.append(dot)
        self.play(FadeIn(dot, scale=1.6), run_time=0.3)

        label = Text(f"{wrong} regions?", font_size=52, color="#FF5252", weight=BOLD)
        label.to_edge(DOWN, buff=1.6)
        self.play(Transform(self.count_label, label) if self.count_label else FadeIn(label), run_time=0.5)
        if self.count_label is None:
            self.count_label = label

        self._show_caption("You'd expect thirty-two", dur)
        wait = dur - 0.3 - 0.5 - 0.5
        if wait > 0:
            self.wait(wait)

    def _seg_reveal(self, seg, dur):
        self._clear_caption()
        n = seg["n"]
        correct = seg.get("correct_count", 31)
        # Last point already added; draw chords to it
        target_dot = self.points[-1]
        target = target_dot.get_center()

        new_lines = []
        for prev_dot in self.points[:-1]:
            line = Line(prev_dot.get_center(), target, color=LINE_COLOR, stroke_width=2.2)
            self.lines.append(line)
            new_lines.append(line)

        self._show_caption("But count carefully", dur)

        if new_lines:
            per_line = max(0.08, min(0.15, (dur * 0.5) / len(new_lines)))
            chord_rt = len(new_lines) * per_line
            self.play(LaggedStart(*[Create(l) for l in new_lines], lag_ratio=0.6, run_time=chord_rt))

        correct_label = Text(f"{correct} regions", font_size=52, color="#69F0AE", weight=BOLD)
        correct_label.to_edge(DOWN, buff=1.6)

        transform_rt = 0.6
        if self.count_label is not None:
            self.play(Transform(self.count_label, correct_label), run_time=transform_rt)
        else:
            self.play(FadeIn(correct_label), run_time=transform_rt)
            self.count_label = correct_label

        wait = dur - 0.5 - chord_rt - transform_rt - 0.2
        if wait > 0:
            self.wait(wait)

    def _seg_outro(self, seg, dur):
        seq = seg.get("sequence", [1, 2, 4, 8, 16, 31])
        items = []
        for i, val in enumerate(seq):
            color = ACCENT if i == len(seq) - 1 else TEXT_COLOR
            t = Text(str(val), font_size=56, color=color)
            if i == len(seq) - 1:
                t = Text(str(val), font_size=64, color=ACCENT, weight=BOLD)
            items.append(t)
            if i < len(seq) - 1:
                arrow = Text(",", font_size=32, color=GRAY)
                items.append(arrow)

        group = VGroup(*items)
        group.arrange(RIGHT, buff=0.25)
        group.move_to(ORIGIN + UP * 1.2)

        final = Text("Don't let it fool you!", font_size=64, color=ACCENT, weight=BOLD)
        final.next_to(group, DOWN, buff=0.8)

        self.play(LaggedStart(*[FadeIn(m, shift=UP * 0.15) for m in items], lag_ratio=0.2, run_time=1.2))
        self.play(FadeIn(final, shift=UP * 0.1), run_time=0.6)

        self._show_caption("Just one shy of a power of two", dur)
        wait = dur - 1.2 - 0.6 - 0.6
        if wait > 0:
            self.wait(wait)
